# Generated by Django 3.0.2 on 2020-02-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_districts_kpis_resulto_sectors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Districts',
        ),
        migrations.DeleteModel(
            name='KPIs',
        ),
        migrations.RemoveField(
            model_name='sectors',
            name='district',
        ),
        migrations.DeleteModel(
            name='Resulto',
        ),
        migrations.DeleteModel(
            name='Sectors',
        ),
    ]
